# Generated by Django 6.1 on 2026-09-01 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_alter_doctor_country_code_alter_doctor_phone'),
        ('patients', '0002_alter_patient_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_doctor_mapping')],
            },
        ),
    ]
