# Generated by Django 6.1 on 2026-08-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='country_code',
            field=models.CharField(max_length=4),
        ),
    ]
